local functions = {}
local player = game.Players.LocalPlayer
local DataManager = require(player.PlayerScripts.Client.Data.DataManager)
local custom_tween = require(game.ReplicatedStorage.Shared.Libraries.CustomTween)
local data = DataManager.Profiles[player]
------------------------ [[ UNIVERSAL FUNCTIONS ]] ------------------------

-- GENERAL RULES
--[[
    1. Folders must have unique names. 
    2. Objects used in Open and Close must have an attribute called
        -> CloseLowestPrio: Num
        -> OpenLowestPrio: Num

    3. UIs must have tag "UI_Obj"
    4. UIs must have
        -> OpenPrioNum
        -> ClosePrioNum
    5. UI must have string attribute for it's target parent name
--]]

-- ACTION RULES
--[[
    1. UI must have a string attribute that holds the function name of it's action
--]]

function functions.Open(UI_Obj)
    local UI = UI_Obj.UI
    local conn = UI_Obj.Connections["Open"]
    if conn then conn:Disconnect() end
    conn = UI.MouseButton1Click:Connect(function()
        Open(UI_Obj)
    end)
end

function functions.Close(UI_Obj)
    local UI = UI_Obj.UI
    local conns = UI_Obj.Connections
    if conns["Close"] then conns["Close"]:Disconnect() end
    conns["Close"] = UI.MouseButton1Click:Connect(function()
        Close(UI_Obj)
    end)
end

function functions.TextInput(UI_Obj)
   local UI = UI_Obj.UI 
   local conn = UI_Obj.Connections["FocusLost"]
   if conn then conn:Disconnect() end
   conn = UI.FocusLost:Connect(function(enterPressed)
        UI_Obj.Text = UI.Text
   end)
end

function Open(UI_Obj)
    for index, folder in UI_Obj.Attributes do
        local UI_Folder = game.ReplicatedStorage.UIs:FindFirstChild(folder)
        if not UI_Folder then continue end

        local Prios = {}
        local UIs = {}
        
        -- Create the UI objects and store in UIs table
        for _, ui in UI_Folder:GetChildren() do
            if not ui:HasTag("UI_Obj") then continue end
            if shared.UI.UIs[ui.Name] then return end
            local ui_Obj = shared.UI.new(ui)
            UIs[ui.Name] = ui_Obj
        end

        -- Segregrate different priorities
        for _, ui in UIs do
            local PrioNum = ui.Attributes.OpenPrio
            if not Prios[PrioNum] then Prios[PrioNum] = {} end
            Prios[PrioNum][ui.UI.Name] = ui 
        end

        -- Initialize highest priority to lowest priority UI
        for i = 1, UI_Obj.Attributes.OpenLowestPrio, 1 do
            for _, ui in Prios[i] do
                ui:Initialize()
            end
        end

        local root_ui = UIs[UI_Obj.UI:GetAttribute("target_root_ui")]    -- Find root UI
        local tween = custom_tween.RepositionUI(root_ui.UI, root_ui.UI.Position - UDim2.fromScale(0, 1), 1)                          -- Animate it
        tween.Completed:Wait()
        tween:Destroy()
    end    
end

function Close(UI_Obj)
    local shared_UIs = shared.UI.UIs
    local Prios = {}
    local UIs = {}

    for _, uiName in UI_Obj.Attributes do
        local ui = shared_UIs[uiName]
        if not ui then continue end
        UIs[uiName] = ui
    end

    local root_ui = UIs[UI_Obj.UI:GetAttribute("target_root_ui")]    -- Find root UI
    root_ui.UI.Parent = UI_Obj.Player.PlayerGui.Trash                -- Reparent it
    local tween = custom_tween.RepositionUI(root_ui.UI, root_ui.UI.Position + UDim2.fromScale(0, 2), 1)                          -- Animate it
    tween.Completed:Wait()
    -- Continue

    for _, ui in UIs do
        local PrioNum = ui.Attributes.ClosePrio
        if not Prios[PrioNum] then Prios[PrioNum] = {} end
        Prios[PrioNum][ui.UI.Name] = ui 
    end

    for i = 1, UI_Obj.Attributes.CloseLowestPrio, 1 do
        for _, ui in Prios[i] do
            ui:Destroy()
        end
    end
    tween:Destroy()
end

------------------------ [[ GAME SPECIFIC FUNCTIONS ]] ------------------------

return functions